# Generated by Django 3.2.4 on 2021-06-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_contributions_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(to='ledger.User'),
        ),
    ]
